server:
  port: 3344

spring:
  application:
    name: springcloud-config-server
    #连接远程仓库
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cchaoqun/SpringCloud_Config_Kuang.git  #https 不是SSH

# 通过config-server 可以连接到git, 访问其中的资源以及配置
